/* GET ALL MOVIES */

export const GET_ALL_MOVIES_PENDING = '[Get movies] GET_ALL_MOVIES_PENDING';
export const GET_ALL_MOVIES_SUCCESS = '[Get movies] GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_ERROR = '[Get movies] GET_ALL_MOVIES_ERROR';

export const IMPORT_FILE_PENDING = '[Import] IMPORT_FILE_PENDING';
export const IMPORT_FILE_SUCCESS = '[Import] IMPORT_FILE_SUCCESS';
export const IMPORT_FILE_ERROR = '[Import] IMPORT_FILE_ERROR';
