/* GET ALL MOVIES */

export const GET_ALL_MOVIES_PENDING = '[Get movies] GET_ALL_MOVIES_PENDING';
export const GET_ALL_MOVIES_SUCCESS = '[Get movies] GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_ERROR = '[Get movies] GET_ALL_MOVIES_ERROR';
